=== Dememedp/Parsers_by_MM_EPAM/parsers/src/main/java/xsd-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.taskManager.com/">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="workers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="worker" type="userType" minOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="managers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="manager" type="userType"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="moderators">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="moderator" type="userType" maxOccurs="2"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="userType">
        <xs:attribute name="name" type="xs:string" default="noName"/>
        <xs:attribute name="login" type="xs:string" use="required"/>
        <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="tasks" type="taskType" />

    <xs:complexType name="taskType">
        <xs:sequence>
            <xs:element name="task">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="date" type="xs:date" use="required"/>
                    <xs:attribute name="note" type="xs:string"/>
                    <xs:attribute name="creator" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Dememedp/Parsers_by_MM_EPAM/parsers/src/main/java/resource/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd-schema.xsd">
    <workers id="wor">
        <worker name="Jane Webster" login="ilovecats66" password="123password456"/>
        <worker name="Chris Kim" login="cricket12" password="klo00Hto" />
        <worker name="Jake Wolf" login="lone_wolf" password="redcoin88" /> <!-- New worker -->
    </workers>

    <managers id="man">
        <manager name="Peter Varik" login="peterparker" password="peterissecret" />
        <manager name="John Smith" login="agent007" password="beourking78" />
    </managers>

    <moderators id="mod">
        <moderator name="Julian King" login="kingofjungle" password="ling90ling" />
    </moderators>

</users>
